### ISSUE TITLE
"Invalid points list" in file ../BOSL2/transforms.scad, line 1375

### ISSUE THREAD

**Issue by spreck** [tallakt/bladegen#1]
Hi there, thanks for this library!

I made a fan blade with PropRep and saw your comment on Thingiverse about this repo so I thought I'd give it a try.

I tried running the sample code you posted, after adding the bladegen and BOSL2 libraries, I'm running the latest OpenSCAD x64 version 2021.01 binary on Windows 10 :

```
use <bladegen/bladegen.scad>

diameter = 200;
hub_r = 15;
hub_h = 12;
hole_d = 6;

root = ellipse_root(r = [0.2, 0.08], rotate = 40.0, radius = 0.10);

difference() {
  union() {
    bladegen(diameter = 200, pitch = 150, inner_radius = 0.3, root = root, blades = 5);
    translate([0, 0, -1]) cylinder(r = hub_r, h = hub_h, center = true);
  }
  cyl(d = hole_d, h = 99, center = true, $fn = 30);
}
```

However I'm getting the following error in the OpenSCAD Console:

 
```
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown function 'oval' in file bladegen.scad, line 70 
ERROR: Assertion 'is_matrix(points)' failed: "Invalid points list" in file ../BOSL2/transforms.scad, line 1375 
TRACE: called by '_apply' in file ../BOSL2/transforms.scad, line 1368 
TRACE: called by 'apply' in file ../BOSL2/transforms.scad, line 551 
TRACE: called by 'rot' in file ../BOSL2/transforms.scad, line 688 
TRACE: called by 'zrot' in file bladegen.scad, line 70 
TRACE: called by 'ellipse_root' in file bladegen.scad, line 8 
Compiling design (CSG Products generation)...
Geometries in cache: 0
Geometry cache size in bytes: 0
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 1 elements!
Compile and preview finished.
Total rendering time: 0:00:00.132
```

Am I doing something wrong or do you get this error as well?

**Comment by tallakt** [comment]
It seems BOSL renamed `oval` to `ellipse`. I have updated bladegen. 

Thanks for your feedback, and good luck with your project.

Since I wrote the project, I have used a design based on bladegen a lot, and its working a charm. I order my props 3D printed from placed like weerg and materialize..

**Comment by tallakt** [comment]
https://github.com/tallakt/bladegen/commit/f977703eabe6e1fead6555cfab68c247f1642c6c
